// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eunneyasrzjjdugmfxda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1bm5leWFzcnpqamR1Z21meGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NDE0ODQsImV4cCI6MjA4NTExNzQ4NH0.HbmYFZPiWymf1LzKPGah4B9ExU4lmtQHwBqmnSU4CEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);